name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run -i --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$HOME:$HOME" \
          -v "$PWD:$PWD" \
          -w "$PWD" \
          openjdk:8-jdk-alpine \
          chmod +x gradlew \
          ./gradlew test
